SELECT DISTINCT S.PRODUCT_ID,
       P.PRODUCT_NAME
  FROM SALES S
  JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
 WHERE S.SALE_DATE BETWEEN DATE_FORMAT('2019-01-01', '%Y-%m-%d') AND DATE_FORMAT('2019-03-31', '%Y-%m-%d')
   AND S.PRODUCT_ID NOT IN (SELECT PRODUCT_ID
                              FROM SALES X
                             WHERE X.SALE_DATE < DATE_FORMAT('2019-01-01', '%Y-%m-%d') OR X.SALE_DATE > DATE_FORMAT('2019-03-31', '%Y-%m-%d'))
;
